x-anchor:
  service: &service
    hostname: localhost
    environment:

      # AUTODONE
      SERVER_PORT: 4000
      SPRING_PROFILES_ACTIVE: test

      # MASTODON
      MASTODON_ADMIN_EMAIL: autodone@localhost
      MASTODON_ADMIN_USERNAME: autodone
      MASTODON_ADMIN_PASSWORD: autodone

      LOCAL_DOMAIN: ${HOSTNAME?External Hostname or IP Address}:3000
      MASTODON_WEB_DOMAIN: ${HOSTNAME?External Hostname or IP Address}:3000

      ALLOW_EMPTY_PASSWORD: true
      MASTODON_DATABASE_HOST: postgres
      MASTODON_DATABASE_NAME: autodone
      MASTODON_DATABASE_USERNAME: autodone
      MASTODON_DATABASE_PASSWORD: autodone
      MASTODON_ELASTICSEARCH_ENABLED: false
      MASTODON_REDIS_HOST: redis

      # POSTGRES
      POSTGRES_DB: autodone
      POSTGRES_USER: autodone
      POSTGRES_PASSWORD: autodone

services:
  autodone:
    <<: *service
    command: mvn -f /src spring-boot:run
    image: docker.io/library/maven:3-eclipse-temurin-17-alpine
    ports: [4000:4000]
    volumes: [.:/src]

  mastodon:
    <<: *service
    image: docker.io/bitnami/mastodon:4.2.9
    ports: [3000:3000]

  postgres:
    <<: *service
    image: docker.io/library/postgres:alpine

  redis:
    <<: *service
    image: docker.io/library/redis:alpine
